<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eMFPatternLanguage" nsURI="http://www.eclipse.org/viatra/query/patternlanguage/emf/EMFPatternLanguage"
    nsPrefix="eMFPatternLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="VQLImportSection" eSuperTypes="http://www.eclipse.org/xtext/xbase/Xtype#//XImportSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageImport" upperBound="-1"
        eType="#//PackageImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternImport" upperBound="-1"
        eType="#//PatternImport" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="ecore:EClass ../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//Pattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassifierConstraint" eSuperTypes="../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//EntityType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass ../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//VariableReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumValue" eSuperTypes="../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//ValueReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternModel" eSuperTypes="../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//PatternModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importPackages" eType="#//VQLImportSection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassType" eSuperTypes="../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//EntityType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" eType="#//PackageImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classname" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceType" eSuperTypes="../../org.eclipse.viatra.query.patternlanguage/model/PatternLanguage.ecore#//RelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refname" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
  </eClassifiers>
</ecore:EPackage>
