<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="events" nsURI="cep.meta" nsPrefix="org.eclipse.viatra.cep.core.metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="EventPattern" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="automaton" eType="ecore:EClass Automaton.ecore#//Automaton"
        eOpposite="Automaton.ecore#//Automaton/eventPattern"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicEventPattern" eSuperTypes="#//EventPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEventPattern" eSuperTypes="#//EventPattern">
    <eOperations name="evaluateParameterBindings" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="event" lowerBound="1" eType="#//Event"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositionEvents" upperBound="-1"
        eType="#//EventPattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" lowerBound="1"
        eType="#//ComplexEventOperator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeWindow" eType="#//TimeWindow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//EventSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventSource" abstract="true">
    <eOperations name="getId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEventOperator" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//ComplexEventOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="NEG" eSuperTypes="#//ComplexEventOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="FOLLOWS" eSuperTypes="#//ComplexEventOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="UNTIL" eSuperTypes="#//ComplexEventOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//ComplexEventOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeWindow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
</ecore:EPackage>
