/*
* generated by Xtext
*/
package org.eclipse.incquery.patternlanguage.emf.tests;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EMFPatternLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.incquery.patternlanguage.emf.ui.internal.EMFPatternLanguageActivator.getInstance().getInjector("org.eclipse.incquery.patternlanguage.emf.EMFPatternLanguage");
	}
	
}
