/*
* generated by Xtext
*/
package org.eclipse.incquery.xcore.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.incquery.xcore.services.IncQueryXcoreGrammarAccess;

public class IncQueryXcoreParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IncQueryXcoreGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.incquery.xcore.parser.antlr.internal.InternalIncQueryXcoreParser createParser(XtextTokenStream stream) {
		return new org.eclipse.incquery.xcore.parser.antlr.internal.InternalIncQueryXcoreParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XIncQueryPackage";
	}
	
	public IncQueryXcoreGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IncQueryXcoreGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
