<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pltest" nsURI="http://www.eclipse.org/viatra/query/patternlanguage/emf/test"
    nsPrefix="pltest">
  <eClassifiers xsi:type="ecore:EClass" name="Base"/>
  <eClassifiers xsi:type="ecore:EClass" name="Common" eSuperTypes="#//Base"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Child1" eSuperTypes="#//Common #//Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a1" eType="#//Common"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child2" eSuperTypes="#//Common #//Interface #//Child3">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a2" eType="#//Common"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrandChild" eSuperTypes="#//Child1 #//Child3"/>
  <eClassifiers xsi:type="ecore:EClass" name="Child3"/>
  <eClassifiers xsi:type="ecore:EClass" name="GrandChild2" eSuperTypes="#//Child2"/>
  <eClassifiers xsi:type="ecore:EClass" name="Red">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="redness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Circle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="red" upperBound="-1" eType="#//Red"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="circumference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhatEver">
    <eStructuralFeatures xsi:type="ecore:EReference" name="someRef" eType="#//Circle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrandChildD" eSuperTypes="#//Child3"/>
  <eClassifiers xsi:type="ecore:EClass" name="GrandGrandChildE" eSuperTypes="#//GrandChildD #//Child1"/>
  <eClassifiers xsi:type="ecore:EClass" name="GrandGrandChildF" eSuperTypes="#//GrandChildD #//Child2"/>
  <eClassifiers xsi:type="ecore:EClass" name="Numbers">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="long" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="float" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="double" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigDecimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
</ecore:EPackage>
