/*
 * generated by Xtext
 */
package org.eclipse.viatra.cep.vepl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VeplUiInjectorProvider implements IInjectorProvider {

    public Injector getInjector() {
        return org.eclipse.viatra.cep.vepl.ui.internal.VeplActivator.getInstance().getInjector(
                "org.eclipse.viatra.cep.vepl.Vepl");
    }

}
