/*
 * generated by Xtext
 */
package org.eclipse.viatra.cep.vepl.ui.contentassist

import org.eclipse.viatra.cep.vepl.ui.contentassist.AbstractVeplProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VeplProposalProvider extends AbstractVeplProposalProvider {
}
