/**
 *
 * $Id$
 */
package org.eclipse.viatra.cep.core.metamodels.events.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.viatra.cep.core.metamodels.events.EventPattern;
import org.eclipse.viatra.cep.core.metamodels.events.LogicalOperator;

/**
 * A sample validator interface for {@link org.eclipse.viatra.cep.core.metamodels.events.ComplexEventPattern}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexEventPatternValidator {
    boolean validate();

    boolean validateCompositionEvents(EList<EventPattern> value);
    boolean validateOperator(LogicalOperator value);
}
