/**
 *
 * $Id$
 */
package org.eclipse.viatra.cep.core.metamodels.events.validation;

import org.eclipse.viatra.cep.core.metamodels.automaton.Automaton;

/**
 * A sample validator interface for {@link org.eclipse.viatra.cep.core.metamodels.events.EventPattern}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventPatternValidator {
    boolean validate();

    boolean validateAutomaton(Automaton value);
    boolean validateId(String value);
}
