/**
 *
 * $Id$
 */
package org.eclipse.viatra.cep.core.metamodels.events.validation;

import org.eclipse.viatra.cep.core.metamodels.events.LogicalOperator;
import org.eclipse.viatra.cep.core.metamodels.events.Time;

/**
 * A sample validator interface for {@link org.eclipse.viatra.cep.core.metamodels.events.TimingOperator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimingOperatorValidator {
    boolean validate();

    boolean validateTime(Time value);
    boolean validateOperator(LogicalOperator value);
}
