/*
 * generated by Xtext
 */
package org.eclipse.viatra.cep.vepl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.viatra.cep.vepl.services.VeplGrammarAccess;

public class VeplParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private VeplGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.viatra.cep.vepl.parser.antlr.internal.InternalVeplParser createParser(XtextTokenStream stream) {
		return new org.eclipse.viatra.cep.vepl.parser.antlr.internal.InternalVeplParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EventModel";
	}
	
	public VeplGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VeplGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
