/*
 * generated by Xtext
 */
package org.eclipse.viatra.cep.vepl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VeplAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/viatra/cep/vepl/parser/antlr/internal/InternalVepl.tokens");
	}
}
