ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::rootdir[:rootdir: .]
ifndef::imagesdir[:imagesdir: {rootdir}/../images]
[[viatra-23]]

= VIATRA 2.3

Release date:: 2019-12-18
More information:: https://projects.eclipse.org/projects/modeling.viatra/releases/2.3.0

== New and Noteworthy

=== Dependency Cleanup

Starting with version 2.3, both the query and transformation runtime works without relying on Guava. This allows avoiding various issues in standalone applications where other users may add a different Guava version than the one used by VIATRA itself. However, there are two important cases to consider:

. The generated pattern matcher code may still depend on Guava if the queries themselves are including `check` or `eval` expressions. For this reason, query projects are still generated with a Guava dependency; but they can be manually removed if unused.
. The infrastructure used to parse VQL files still requires Guava to function.

=== Code Generator Updates

Starting with this version, it is possible to disable query group generation (and the validation rules related to it) via customizing the language configuration module. The built-in standalone parser modules disables query group generation, but by default this functionality will stay enabled. The simplest way to rely on this updated generator is the following:

[source,xtend]
----
val String pattern = '''
    import "http://www.eclipse.org/emf/2002/Ecore";
    
    pattern b(c : EClass) {
     EClass.name(c, "someName2");
    }
'''

val parser = new PatternParserBuilder()
    .withInjector(new EMFPatternLanguageStandaloneSetup().createStandaloneInjector)
    .build
val uri = URI.createFileURI("b.vql")
val results = parser.parse(pattern, uri)
----

=== Base Index Profiler

In order to measure the effects of VIATRA, version 2.3 includes a simple profiler for the base index itself that measures the time spent inside the adapters VIATRA uses to initialize the indexes and keep them up-to-date. Given the use of the profiler results in reduced performance, it is turned off by default, but can be enabled with the appropriate base index option.

Usage:

[source,java]
----
// Initialized profiling during model load
BaseIndexOptions options = new BaseIndexOptions()
    .withIndexProfilingEnabledMode(ProfilerMode.ENABLED);
NavigationHelper baseIndex = ... ;
val profiler = new BaseIndexProfiler(baseIndex)

doTasks(baseIndex);

long count = profiler.getNotificationCount(); 
long time = profiler.totalMeasuredTimeInMS);
---- 

== Migrating to VIATRA 2.3

The `viatra-query-runtime` and `viatra-transformation-runtime` Maven modules do not add any version of Guava to the classpath anymore. If the actual project using VIATRA depends on Guava, it can be added as dependency.