ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::rootdir[:rootdir: .]
ifndef::imagesdir[:imagesdir: {rootdir}/../images]
[[viatra-20]]
= VIATRA 2.0

== Migrating to VIATRA 2.0

=== Dependency updates
Update minimum version of required dependencies 

=== Deprecated code removal

All code marked as deprecated has been removed from the codebase. Additionally, further components were removed
* CEP has been removed
* Xcore integration has been removed
* C++ local search implementatation has been removed
* Query-by-example has been removed
* EVM-JDT integration has been removed

=== Reduction of Guava uses

There were a few cases, where Guava types such as Functions or Predicates were visible in the API. In VIATRA 2.0, the trivial method calls were removed (to be handled via direct method references), while the remaining ones were replaced by the alternatives built-in to the Java 8 standard library. The following methods were affected:

 * `PQueries#parameterDirectionPredicate`: returns Java 8 predicate
 * `PQueries#queryNameFunction`: can be replaced by a method reference of `PQuery::getFullyQualifiedName`
 * `PQueries#parameterNameFunction`: can be replaced by a method reference of `PParameter::getName`
 * `PQueries#queryOfReferenceFunction`: can be replaced by a method reference of `IQueryReference::getReferredQuery`
 * `PQueries#directlyReferencedQueriesFunction`: returns a Java 8 function
 * `PQueries#queryStatusPredicate`: returns a Java 8 predicate
 
=== Avoid returning null values in the API

A few APIs in VIATRA returned null if no possible values could be found. Given VIATRA 2.0 depends on Java 8, such APIs were reworked to return url:https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html[Optional] values instead.

The affected methods are the following:

 * PQueryHeader#getFirstAnnotationByName

If the old behavior of returning `null` values is necessary the `Optional.orElse` call can be used, e.g. `query.getFirstAnnotationByName("Constraint").orElse(null);`

=== Exception handling consolidation
Before VIATRA 2.0, the various APIs of the Query component threw a set of different *checked* exceptions: ViatraQueryException, ViatraBaseException and QueryProcessingException (and specialized versions of them). For version 2.0, these exceptions were updated in two ways:

1. All of them are now runtime exceptions, making it unnecessary to explicitly catch them. This makes it easier to put query processing code into lambda expressions, however, makes it entirely the developers responsibility to handle these exceptions as they happen.
2. All of them have now a common base exception called ViatraQueryRuntimeException - this class can be used anywhere in catch blocks if appropriate.