ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::rootdir[:rootdir: .]
ifndef::imagesdir[:imagesdir: {rootdir}/../images]
[[viatra-27]]

= VIATRA 2.7

Release date:: 2022-03-xx
More information:: https://projects.eclipse.org/projects/modeling.viatra/releases/2.7.0

== New and Noteworthy

In addition to bugfixes, VIATRA 2.7 introduces a new language feature: now it is possible to reference Java constants, more precisely, public static final fields of Java classes from pattern specifications.

[source,vql]
----
pattern maxInteger(value : java Integer) {
  value == java Integer::MAX_VALUE;
}
----

Another new language feature in version 2.7 is eval unwinding: it is now possible to return multiple different values from any given attribute value. This feature is useful for extracting data from otherwise unstructured information, e.g. multiple URLs from a specific documentation field.

[source,vql]
----
/* Match set are the tuples <value=2>, <value=3> and <value=5>*/
incremental pattern firstThreePrimes(value : java Integer) {
  value == eval unwind (newHashSet(2, 3, 5));
}
----


== Migrating to VIATRA 2.7

As the eval unwinding feature introduces the `unwind` keyword to the language, metamodels providing features named the same need to be escaped.