ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::rootdir[:rootdir: .]
ifndef::imagesdir[:imagesdir: {rootdir}/../images]
[[viatra-20]]
= VIATRA 2.0

== Migrating to VIATRA 2.0

=== Dependency updates
Update minimum version of required dependencies 

=== Deprecated code removal

All code marked as deprecated has been removed from the codebase. Additionally, further components were removed
* CEP has been removed
* Xcore integration has been removed
* C++ local search implementatation has been removed
* Query-by-example has been removed
* EVM-JDT integration has been removed

=== Reduction of Guava uses

There were a few cases, where Guava types such as Functions or Predicates were visible in the API. In VIATRA 2.0, the trivial method calls were removed (to be handled via direct method references), while the remaining ones were replaced by the alternatives built-in to the Java 8 standard library. The following classes and methods were affected:

 * `PQueries#parameterDirectionPredicate`: returns Java 8 predicate
 * `PQueries#queryNameFunction`: can be replaced by a method reference of `PQuery::getFullyQualifiedName`
 * `PQueries#parameterNameFunction`: can be replaced by a method reference of `PParameter::getName`
 * `PQueries#queryOfReferenceFunction`: can be replaced by a method reference of `IQueryReference::getReferredQuery`
 * `PQueries#directlyReferencedQueriesFunction`: returns a Java 8 function
 * `PQueries#queryStatusPredicate`: returns a Java 8 predicate
 * `CorePatternLanguageHelper#getReferencedPatternsTransitive` accepts a Java 8 predicate as a parameter
 * `ConflictSetIterator` accepts a Java 8 predicate as a constructor parameter
 * `BatchTransformationStatements#fireUntil` accepts a Java 8 predicate as a condition
 * `RecordingJob` does not record all created commands in a Table anymore; if the created commands are to be accessed, the RecordingJob should be initialized with a new command recorder instance that will be notified with each command after it was executed
 * The `QueryResultMultimap` and `EVMBasedQueryResultMultimap` classes provided a Multimap interface for query matches; given they limited uses through the years, were simply removed.


=== Removal of unnecessary Xtend library dependencies

The transformation API used the `Pair` class from the Xtend standard library to rely the `->` (mapped to) operator to define filters based on name mappings. In version 2.0, the underlying code was changed to rely on `Map.Entry` classes from the Java standard library. 

The following methods were affected by this change:

 * `MatchParameterFilter` accepts an array of Map Entries instead of Xtend Pairs
 * `BatchTransformationStatements` accepts an array of Map Entries instead of Xtend Pairs as parameters on various methods
 * `EventDrivenTransformationBuilder#filter` accepts an array of Map Entries instead of Xtend Pairs

To migrate your code, you can do one of the following:

 * If you are using Xtend code, and the `"name" -> value` syntax does not compile anymore, add the following import declaration in the header: `import static extension org.eclipse.viatra.transformation.runtime.emf.transformation.TransformationExtensions.*`
 * If you are not using Xtend, or you don't want to rely on the mapped to operator, simply instantiate these entries with the call `new SimpleEntry<>("name", value)`.

=== Avoid returning null values in the API

A few APIs in VIATRA returned null if no possible values could be found. Given VIATRA 2.0 depends on Java 8, such APIs were reworked to return url:https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html[Optional] values instead.

The affected methods are the following:

 * PQueryHeader#getFirstAnnotationByName
 * CorePatternLanguageHelper#getFirstAnnotationByName
 * CorePatternLanguageHelper#getParameterByName

If the old behavior of returning `null` values is necessary the `Optional.orElse` call can be used, e.g. `query.getFirstAnnotationByName("Constraint").orElse(null);`

=== Exception handling consolidation
Before VIATRA 2.0, the various APIs of the Query component threw a set of different *checked* exceptions: ViatraQueryException, ViatraBaseException and QueryProcessingException (and specialized versions of them). For version 2.0, these exceptions were updated in two ways:

1. All of them are now runtime exceptions, making it unnecessary to explicitly catch them. This makes it easier to put query processing code into lambda expressions, however, makes it entirely the developers responsibility to handle these exceptions as they happen.
2. All of them have now a common base exception called ViatraQueryRuntimeException - this class can be used anywhere in catch blocks if appropriate.