ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::rootdir[:rootdir: .]
ifndef::imagesdir[:imagesdir: {rootdir}/../images]
[[viatra-27]]

= VIATRA 2.7

Release date:: 2022-03-16
More information:: https://projects.eclipse.org/projects/modeling.viatra/releases/2.7.0

== New and Noteworthy

In addition to bugfixes, VIATRA 2.7 introduces two new language features: the capability to reference *Java constants*, and the use of *eval unwinding*.

For the first case, Java constants more precisely, public static final fields of Java classes from pattern specifications everywhere where variables or constant literals can be used.

[source,vql]
----
pattern maxInteger(value : java Integer) {
  value == java Integer::MAX_VALUE;
}
----

Eval unwinding allows the processing of collections inside pattern bodies: by writing a specific eval expression with the marked with the `unwind` keyword, the returned Set is processed one by one (as separate matches). This feature is useful for extracting data from otherwise unstructured information, e.g. multiple URLs from a specific documentation field.

[source,vql]
----
/* Match set are the tuples <value=2>, <value=3> and <value=5>*/
incremental pattern firstThreePrimes(value : java Integer) {
  value == eval unwind (newHashSet(2, 3, 5));
}
----


== Migrating to VIATRA 2.7

As the eval unwinding feature introduces the `unwind` keyword to the language, metamodels providing features named the same need to be escaped.