/*
 * generated by Xtext
 */
package org.eclipse.viatra.cep.vepl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.viatra.cep.vepl.ui.internal.VeplActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VeplExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VeplActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VeplActivator.getInstance().getInjector(VeplActivator.ORG_ECLIPSE_VIATRA_CEP_VEPL_VEPL);
	}
	
}
